//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reto.Models.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class WebRecord
    {
        public string WebRecordId { get; set; }
        public string ActionLink { get; set; }
        public string PostData { get; set; }
        public string ClientIP { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string CreateUser { get; set; }
    }
}
